name = "EcoEvoSim"
uuid = "a1b2c3d4-e5f6-7890-abcd-ef1234567890"
keywords = ["ecology", "evolution", "simulation", "ODE"]
license = "MIT"
version = "0.1.0"
authors = ["György Barabás <dysordys@protonmail.com>"]
description = "High‑level eco‑evolutionary simulation framework."
repository = "https://github.com/dysordys/EcoEvoSim.git"

[deps]
Distributions = "31c24e10-a181-5473-b8eb-7969acd0382f"
LinearAlgebra = "37e2e46d-f89d-539d-b4ee-838fcccc9c8e"
NonlinearSolve = "8913a72c-1f9b-4ce2-8d82-65094dcecaec"
OrderedCollections = "bac558e1-5e72-5ebc-8fee-abe8a469f55d"
OrdinaryDiffEq = "1dea7af3-3e70-54e6-95c3-0bf5283fa5ed"
Random = "9a3f8284-a2c9-5f02-9a11-845980a1fd5c"
SteadyStateDiffEq = "9672c7b4-1e72-59bd-8a11-6ac3964bc41f"

[weakdeps]
GLMakie = "e9467ef8-e4e7-5192-8a1a-b1aee30e663a"
Plots = "91a5bcdd-55d7-5caf-9e0b-520d859cae80"

[extensions]
EcoEvoSimGLMakieExt = "GLMakie"
EcoEvoSimPlotsExt = "Plots"

[compat]
Distributions = "0.25"
GLMakie = "0.11"
LinearAlgebra = "1.0"
NonlinearSolve = "4.19.1"
OrderedCollections = "1.0"
OrdinaryDiffEq = "6"
Plots = "1.38"
Random = "1.0"
SteadyStateDiffEq = "2"
julia = "1.9"

[extras]
Plots = "91a5bcdd-55d7-5caf-9e0b-520d859cae80"
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Plots", "Test"]
